version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    expose:
      - "80"
      - "443"
    restart: always
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m
